name: Update Archives on HTML File Change

on:
  push:
    branches:
      - main # 監聽主要分支的推送事件

jobs:
  update-archives:
    runs-on: ubuntu-latest

    steps:
      # 檢出程式碼
      - name: Checkout Code
        uses: actions/checkout@v3

      # 確保完整的提交記錄
      - name: Fetch full git history
        run: git fetch --depth=2 || true

      - name: Get changed HTML files
        id: get_html_files
        run: |
          # 獲取最近的提交中新增或刪除的 HTML 檔案，排除 index.html
          ADDED_FILES=$(git diff --name-status HEAD^ HEAD | grep '^A' | grep '\.html' | grep -v 'index.html' | awk '{$1=""; print substr($0,2)}' || echo "")
          DELETED_FILES=$(git diff --name-status HEAD^ HEAD | grep '^D' | grep '\.html' | awk '{$1=""; print substr($0,2)}' || echo "")
          echo "ADDED_FILES: $ADDED_FILES"
          echo "DELETED_FILES: $DELETED_FILES"
          echo "added_files=$ADDED_FILES" >> $GITHUB_ENV
          echo "deleted_files=$DELETED_FILES" >> $GITHUB_ENV

      - name: Update index.html
        run: |
          # 更新 index.html 中的列表
          if [ -n "$added_files" ]; then
            for file in $added_files; do
              echo "$file"
              # 將每個新增的 HTML 檔案連結添加到 link-list 的 ul 中
              sed -i "/<ul class=\"link-list\">/a\\
              <li><a href=\"$file\">$(basename "$file")</a></li>\\
              " index.html
            done
          fi

          if [ -n "$deleted_files" ]; then
            for file in $deleted_files; do
              # 從 archives 的 ul 中移除已刪除的檔案連結
              sed -i -E "/<ul class=\"link-list\">/,/<\/ul>/s|<li><a href=\"$file\">$(basename "$file")</a></li>||" index.html
            done
          fi

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update archives in index.html"
            git push
          else
            echo "No changes to commit"
          fi
